/**
 * ================================================================
 *  CRE Workflow: mission-start
 *  CHAINLINK SERVICE: CRE / Keystone (Decentralized Oracle Network)
 * ================================================================
 *
 *  PURPOSE:
 *    Listens for the on-chain `InvestigationSubmitted` event emitted by
 *    GameMaster.sol whenever a player investigates a city. The workflow
 *    then determines whether the player picked the correct city (where
 *    Carmen is hiding), selects a "true" or "false" clue, encrypts it
 *    with the player's ECIES public key, and delivers the encrypted
 *    clue back on-chain through the GameMasterProxy.
 *
 *    If the player guessed correctly AND has collected at least 3 clues,
 *    the workflow also triggers a capture resolution — ending the
 *    mission and minting a trophy NFT for the player.
 *
 *  CHAINLINK CRE INTEGRATION:
 *    This workflow runs inside Chainlink's CRE (Compute Runtime Environment),
 *    also known as Keystone. CRE compiles this TypeScript code into WASM
 *    and deploys it to a DON (Decentralized Oracle Network) — a set of
 *    independent Chainlink node operators that execute the logic in parallel,
 *    reach consensus on the result, and sign it with a threshold signature.
 *
 *    KEY PROPERTIES:
 *    - DECENTRALIZED: No centralized server. The game logic runs across
 *      multiple independent Chainlink nodes. No single point of failure.
 *    - TAMPER-PROOF: The DON signs every output with a threshold ECDSA
 *      signature. The on-chain GameMasterProxy verifies this signature
 *      before accepting any clue or capture resolution.
 *    - TRUSTLESS: Neither the game developer nor any single oracle node
 *      can manipulate clue generation, strength scores, or capture outcomes.
 *    - EVENT-DRIVEN: Triggered by an on-chain LogTrigger (EVM event),
 *      not a centralized webhook or API call.
 *
 *  DATA FLOW:
 *    1. Player calls submitInvestigation() on GameMaster.sol
 *    2. GameMaster emits InvestigationSubmitted event on Ethereum Sepolia
 *    3. CRE DON detects the event via LogTrigger capability
 *    4. DON nodes execute this WASM workflow in parallel:
 *       a. Read on-chain state (salt, cities, mission, player public key)
 *       b. Brute-force the VRF-derived targetHash to find Carmen's city
 *       c. Select contextual clue from scenario pool (true/false)
 *       d. Calculate deterministic strength score from salt entropy
 *       e. ECIES-encrypt the clue with the player's secp256k1 public key
 *    5. DON nodes reach consensus and produce a signed report
 *    6. Report is delivered on-chain via runtime.report() + writeReport()
 *    7. GameMasterProxy verifies the Keystone signature and routes the
 *       action to GameMaster.receiveClue() (or resolveCapture())
 *
 *  WHY CRE INSTEAD OF A CENTRALIZED SERVER:
 *    - A centralized server could cheat: send wrong clues, fake strength
 *      scores, or prevent captures. CRE makes this impossible.
 *    - Multiple DON nodes must agree on the result before it reaches
 *      the blockchain, providing Byzantine fault tolerance.
 *    - The player-facing contract (GameMasterProxy) ONLY accepts reports
 *      signed by the authorized CRE workflow, preventing spoofing.
 *
 *  CHAINLINK SERVICES USED IN THIS WORKFLOW:
 *    - CRE/Keystone: WASM execution, LogTrigger, consensus, signed reports
 *    - EVMClient: Cross-chain reads from Sepolia (callContract / EVM Read)
 *    - writeReport: On-chain writes via Keystone Forwarder (EVM Write)
 *    - VRF v2.5: Salt used here was generated by VRF in startMission()
 *
 *  AI CLUE GENERATION:
 *    The workflow includes a generateAIClue function (async, for CRE v2)
 *    that creates contextual clues via OpenAI based on the scenario,
 *    city details, and whether the investigation was correct.
 *    Currently uses scenario-based clues as fallback.
 *
 *  CONFIG:
 *    - chainSelectorName, gameMasterAddress, proxyAddress, gasLimit
 *    - openaiApiKey: (optional) for AI-generated clues in CRE v2
 *    - openaiModel: (optional) model name
 *
 *  IMPORTANT CONSTRAINTS:
 *    - @noble/* libs MUST stay on v1.x (v2.x breaks CRE WASM compilation)
 *    - Handler must be synchronous (no async/await inside the handler)
 *    - All EVM reads use .result() which blocks synchronously in CRE
 * ================================================================
 */

import {
  EVMClient,
  handler,
  Runner,
  getNetwork,
  hexToBase64,
  bytesToHex,
  encodeCallMsg,
  LATEST_BLOCK_NUMBER,
  type Runtime,
  type EVMLog,
} from "@chainlink/cre-sdk"
import {
  keccak256,
  toBytes,
  encodeFunctionData,
  decodeFunctionResult,
  decodeEventLog,
  encodeAbiParameters,
  parseAbiParameters,
  parseAbi,
  zeroAddress,
} from "viem"
import { eciesEncrypt } from "./ecies"

// ============================================================
//  Config — populated from workflow.yaml target settings
// ============================================================
type Config = {
  chainSelectorName: string
  gameMasterAddress: string
  proxyAddress: string
  gasLimit: string
  openaiApiKey?: string   // Optional — for AI-generated clues (CRE v2)
  openaiModel?: string    // Optional — model name
}

// ============================================================
//  ABI fragments
// ============================================================
const GameMasterABI = parseAbi([
  "function getMission(uint256) view returns (address,uint256,bytes32,uint8,uint8,uint8)",
  "function getMissionSalt(uint256) view returns (bytes32)",
  "function getValidCities() view returns (uint256[])",
  "function getMissionClues(uint256) view returns ((uint8,bytes32,string,uint256,uint8)[])",
  "function getPlayerPublicKey(address) view returns (bytes)",
  "function getMissionFragmentCount(uint256) view returns (uint8)",
  "function deriveCarmenWallet(bytes32) view returns (address)",
  "event InvestigationSubmitted(uint256 indexed missionId, address indexed player, uint256 chainId)",
])

// ============================================================
//  Scenarios
// ============================================================
import scenariosData from "../data/scenarios.json"

type ScenarioClue = { type: number; text: string }
type Scenario = {
  id: string
  title: string
  cities: Record<string, { name: string; emoji: string; chain: string }>
  cityClues: Record<string, { landmark: string; culture: string }>
  clues: { true: ScenarioClue[]; false: ScenarioClue[] }
}

function getScenario(missionId: bigint): Scenario {
  const scenarios = scenariosData.scenarios
  if (!scenarios || scenarios.length === 0) {
    throw new Error("No scenarios configured in scenarios.json")
  }
  const index = Number(missionId - BigInt(1)) % scenarios.length
  return scenarios[index] as Scenario
}

// Action codes — must match GameMasterProxy.sol constants
const ACTION_RECEIVE_CLUE = 1
const ACTION_RESOLVE_CAPTURE = 2
const ACTION_RECEIVE_WALLET_FRAGMENT = 4

const ZERO_HASH = "0x0000000000000000000000000000000000000000000000000000000000000000"

// ============================================================
//  Helper: read contract — reduces boilerplate for EVM reads
// ============================================================
function readContract(
  evmClient: EVMClient,
  runtime: Runtime<Config>,
  address: string,
  callData: `0x${string}`,
): Uint8Array {
  return evmClient
    .callContract(runtime, {
      call: encodeCallMsg({
        from: zeroAddress,
        to: address as `0x${string}`,
        data: callData,
      }),
      blockNumber: LATEST_BLOCK_NUMBER,
    })
    .result()
    .data
}

// ============================================================
//  Helper: convert hex public key to Uint8Array
// ============================================================
function parsePubKey(pubKeyHex: string, log: (msg: string) => void): Uint8Array | null {
  const clean = pubKeyHex.startsWith("0x") ? pubKeyHex.slice(2) : pubKeyHex
  if (clean.length !== 130 || !/^[0-9a-fA-F]+$/.test(clean)) {
    log(`ERROR: Invalid public key format (length=${clean.length})`)
    return null
  }
  const bytes = new Uint8Array(clean.length / 2)
  for (let i = 0; i < bytes.length; i++) {
    bytes[i] = parseInt(clean.slice(i * 2, i * 2 + 2), 16)
  }
  return bytes
}

// ============================================================
//  Helper: deterministic strength calculation
// ============================================================
function calculateStrength(salt: `0x${string}`, clueIndex: number, isCorrectCity: boolean): number {
  const hash = keccak256(
    encodeAbiParameters(parseAbiParameters("bytes32, uint256, string"), [salt, BigInt(clueIndex), "strength"])
  )
  const raw = Number(BigInt(hash) % BigInt(256))

  if (isCorrectCity) {
    // correct city: range 40-95 (can exceed 65 → generates evidence)
    return 40 + (raw % 56)
  } else {
    // wrong city: range 20-55 (never exceeds 65)
    return 20 + (raw % 36)
  }
}

// ============================================================
//  AI Clue Generation (async — for CRE v2)
//
//  Creates contextual, dynamic clues via OpenAI API based on
//  the scenario, the investigated city, and whether it's correct.
//  Falls back to scenario-based clues when unavailable.
// ============================================================
async function generateAIClue(
  scenario: Scenario,
  carmenCityId: string,
  investigatedCityId: string,
  isCorrect: boolean,
  clueNumber: number,
  apiKey: string,
  model: string,
  log: (msg: string) => void,
): Promise<{ type: number; text: string }> {
  const carmenCity = scenario.cities[carmenCityId]
  const investigatedCity = scenario.cities[investigatedCityId]
  const carmenClue = scenario.cityClues[carmenCityId]
  const investigatedClue = scenario.cityClues[investigatedCityId]

  const systemPrompt = `You are a clue generator for "Carmen Sandiego On-Chain," a blockchain mystery game. You write concise, atmospheric clues in a noir detective style. Each clue should blend real-world cultural details with blockchain/Web3 references. Keep clues under 80 words.`

  let userPrompt: string
  if (isCorrect) {
    userPrompt = `Write a TRUE clue (#${clueNumber + 1}) for a detective game.

Carmen IS in: ${carmenCity?.name || "unknown"} (${carmenCity?.chain || "unknown"})
Landmarks: ${carmenClue?.landmark || "unknown"}, Culture: ${carmenClue?.culture || "unknown"}
Scenario: "${scenario.title}"

The clue should subtly hint at ${carmenCity?.name} through cultural references and blockchain activity. Do NOT name the city directly. Make it feel like intelligence gathered from the field.`
  } else {
    userPrompt = `Write a FALSE (misleading) clue (#${clueNumber + 1}) for a detective game.

Player investigated: ${investigatedCity?.name || "unknown"} — Carmen is NOT here.
City details: ${investigatedClue?.landmark || "unknown"}, ${investigatedClue?.culture || "unknown"}
Scenario: "${scenario.title}"

The clue should suggest Carmen MIGHT be in ${investigatedCity?.name} but include subtle hints it's a dead end. End with a slightly mocking tone.`
  }

  try {
    log(`Calling AI API for ${isCorrect ? "true" : "false"} clue...`)

    const response = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model,
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt },
        ],
        max_tokens: 200,
        temperature: 0.85,
      }),
    })

    if (!response.ok) throw new Error(`AI API returned ${response.status}`)

    const data = await response.json() as {
      choices: Array<{ message: { content: string } }>
    }

    const clueText = data.choices?.[0]?.message?.content
    if (!clueText) throw new Error("Empty AI response")

    log(`AI clue generated (${clueText.length} chars)`)
    return { type: 0, text: clueText }
  } catch (err) {
    log(`AI clue generation failed: ${err}. Using scenario clue.`)
    const pool = isCorrect ? scenario.clues.true : scenario.clues.false
    return pool[clueNumber % pool.length]
  }
}

// ============================================================
//  Handler: onInvestigationSubmitted
// ============================================================
const onInvestigationSubmitted = (runtime: Runtime<Config>, log: EVMLog): Record<string, never> => {
  const config = runtime.config

  const network = getNetwork({
    chainFamily: "evm",
    chainSelectorName: config.chainSelectorName,
    isTestnet: true,
  })
  if (!network) throw new Error(`Network not found: ${config.chainSelectorName}`)

  const evmClient = new EVMClient(network.chainSelector.selector)
  const gm = config.gameMasterAddress

  // ── Step 1: Decode InvestigationSubmitted event ──
  const topics = log.topics.map((t) => bytesToHex(t)) as [`0x${string}`, ...`0x${string}`[]]
  const data = bytesToHex(log.data)

  const decoded = decodeEventLog({
    abi: GameMasterABI,
    data,
    topics,
  })

  if (decoded.eventName !== "InvestigationSubmitted") {
    throw new Error(`Unexpected event: ${decoded.eventName}`)
  }

  const { missionId, player, chainId: investigatedChainId } = decoded.args
  runtime.log(`Investigation: mission=${missionId}, player=${player}, chainId=${investigatedChainId}`)

  // ── Step 2: Read salt ──
  const saltData = readContract(evmClient, runtime, gm, encodeFunctionData({
    abi: GameMasterABI,
    functionName: "getMissionSalt",
    args: [missionId],
  }))
  const salt = decodeFunctionResult({
    abi: GameMasterABI,
    functionName: "getMissionSalt",
    data: bytesToHex(saltData),
  }) as `0x${string}`
  runtime.log(`Salt: ${salt}`)

  if (salt === ZERO_HASH) {
    runtime.log("WARN: Salt is zero — VRF not yet fulfilled. Skipping.")
    return {}
  }

  // ── Step 3: Read valid cities ──
  const citiesData = readContract(evmClient, runtime, gm, encodeFunctionData({
    abi: GameMasterABI,
    functionName: "getValidCities",
  }))
  const cities = decodeFunctionResult({
    abi: GameMasterABI,
    functionName: "getValidCities",
    data: bytesToHex(citiesData),
  }) as bigint[]
  runtime.log(`Valid cities: ${cities.join(", ")}`)

  // ── Step 4a: Read mission state ──
  const missionData = readContract(evmClient, runtime, gm, encodeFunctionData({
    abi: GameMasterABI,
    functionName: "getMission",
    args: [missionId],
  }))
  const [, , targetHash, cluesReceived, ,] = decodeFunctionResult({
    abi: GameMasterABI,
    functionName: "getMission",
    data: bytesToHex(missionData),
  }) as [string, bigint, string, number, number, number]
  runtime.log(`TargetHash: ${targetHash}, cluesReceived: ${cluesReceived}`)

  // ── Step 4b: Read player public key ──
  const pubKeyData = readContract(evmClient, runtime, gm, encodeFunctionData({
    abi: GameMasterABI,
    functionName: "getPlayerPublicKey",
    args: [player],
  }))
  const playerPubKeyHex = decodeFunctionResult({
    abi: GameMasterABI,
    functionName: "getPlayerPublicKey",
    data: bytesToHex(pubKeyData),
  }) as `0x${string}`
  runtime.log(`Player public key: ${playerPubKeyHex.slice(0, 20)}...`)

  // ── Step 5: Brute-force — find Carmen's actual city ──
  let carmenCity: bigint | undefined
  for (const city of cities) {
    const candidateHash = keccak256(
      encodeAbiParameters(parseAbiParameters("uint256, bytes32"), [city, salt])
    )
    if (candidateHash === targetHash) {
      carmenCity = city
      break
    }
  }

  if (carmenCity === undefined) {
    runtime.log(`ERROR: Could not determine Carmen's location.`)
    runtime.log(`  targetHash=${targetHash}, salt=${salt}, cities=[${cities.join(",")}]`)
    return {}
  }
  runtime.log(`Carmen is in city: ${carmenCity}`)

  // ── Step 6: Select clue (true or false) ──
  const isCorrectCity = investigatedChainId === carmenCity
  runtime.log(`Player investigated ${investigatedChainId}, correct=${isCorrectCity}`)

  const scenario = getScenario(missionId)

  // Scenario-based clue selection (AI path ready for CRE v2)
  // TODO: When CRE supports async handlers, replace with:
  // const aiClue = await generateAIClue(scenario, carmenCity.toString(), investigatedChainId.toString(),
  //   isCorrectCity, cluesReceived, config.openaiApiKey!, config.openaiModel!, runtime.log)
  // clueText = aiClue.text; clueType = aiClue.type;
  const cluePool = isCorrectCity ? scenario.clues.true : scenario.clues.false
  const clueIndex = Number(cluesReceived) % cluePool.length
  const selectedClue = cluePool[clueIndex]
  const clueText = selectedClue.text
  const clueType = selectedClue.type

  // ── Step 6b: Calculate deterministic strength ──
  const strength = calculateStrength(salt, Number(cluesReceived), isCorrectCity)
  runtime.log(`Clue strength: ${strength} (threshold=65, correct=${isCorrectCity})`)

  // ── Step 7: Encrypt clue with ECIES ──
  const contentHash = keccak256(toBytes(clueText))

  const pubKeyBytes = parsePubKey(playerPubKeyHex, runtime.log)
  if (!pubKeyBytes) return {}

  const saltBytes = toBytes(salt as `0x${string}`)
  const encryptedClue = eciesEncrypt(pubKeyBytes, clueText, saltBytes)
  runtime.log(`Clue encrypted (${encryptedClue.length} hex chars)`)

  // ── Step 8: Send clue report ──
  const clueData = encodeAbiParameters(
    parseAbiParameters("uint256, uint8, bytes32, string, uint8"),
    [missionId, clueType, contentHash as `0x${string}`, encryptedClue, strength]
  )
  const clueReport = encodeAbiParameters(
    parseAbiParameters("uint8, bytes"),
    [ACTION_RECEIVE_CLUE, clueData as `0x${string}`]
  )

  runtime.log("Sending clue report to proxy...")
  const clueReportResponse = runtime
    .report({
      encodedPayload: hexToBase64(clueReport),
      encoderName: "evm",
      signingAlgo: "ecdsa",
      hashingAlgo: "keccak256",
    })
    .result()

  evmClient
    .writeReport(runtime, {
      receiver: config.proxyAddress,
      report: clueReportResponse,
      gasConfig: { gasLimit: config.gasLimit },
    })
    .result()

  runtime.log("Clue delivered successfully!")

  // ── Step 8b: Wallet fragment (only for strong clues — evidence threshold) ──
  const EVIDENCE_THRESHOLD = 65
  if (strength > EVIDENCE_THRESHOLD) {
    runtime.log(`Strong clue (${strength} > ${EVIDENCE_THRESHOLD})! Generating wallet fragment...`)

    // Read current fragment count
    const fragCountData = readContract(evmClient, runtime, gm, encodeFunctionData({
      abi: GameMasterABI,
      functionName: "getMissionFragmentCount",
      args: [missionId],
    }))
    const fragmentCount = Number(decodeFunctionResult({
      abi: GameMasterABI,
      functionName: "getMissionFragmentCount",
      data: bytesToHex(fragCountData),
    }))
    runtime.log(`Current fragment count: ${fragmentCount}`)

    // Derive Carmen's wallet from salt
    const carmenWalletData = readContract(evmClient, runtime, gm, encodeFunctionData({
      abi: GameMasterABI,
      functionName: "deriveCarmenWallet",
      args: [salt],
    }))
    const carmenWallet = decodeFunctionResult({
      abi: GameMasterABI,
      functionName: "deriveCarmenWallet",
      data: bytesToHex(carmenWalletData),
    }) as `0x${string}`

    // Extract wallet hex (40 chars, no 0x prefix)
    const walletHex = carmenWallet.slice(2).toLowerCase()
    runtime.log(`Carmen wallet: 0x${walletHex.slice(0, 8)}...`)

    // Calculate fragment position deterministically from salt + fragmentCount
    const FRAGMENT_LENGTH = 5
    const positionHash = keccak256(
      encodeAbiParameters(parseAbiParameters("bytes32, uint256"), [salt, BigInt(fragmentCount)])
    )
    const startIndex = Number(BigInt(positionHash) % BigInt(40 - FRAGMENT_LENGTH + 1))

    // Extract the fragment chars
    const fragmentChars = walletHex.slice(startIndex, startIndex + FRAGMENT_LENGTH)
    runtime.log(`Fragment #${fragmentCount}: pos=${startIndex}, chars="${fragmentChars}"`)

    // Encrypt fragment with player's ECIES key
    const fragmentPayload = JSON.stringify({
      fragmentIndex: fragmentCount,
      startIndex,
      length: FRAGMENT_LENGTH,
      chars: fragmentChars,
    })
    const fragmentContentHash = keccak256(toBytes(fragmentPayload))
    const encryptedFragment = eciesEncrypt(pubKeyBytes, fragmentPayload, saltBytes)

    // Send wallet fragment report
    const fragData = encodeAbiParameters(
      parseAbiParameters("uint256, uint8, uint8, bytes32, string"),
      [missionId, startIndex, FRAGMENT_LENGTH, fragmentContentHash as `0x${string}`, encryptedFragment]
    )
    const fragReport = encodeAbiParameters(
      parseAbiParameters("uint8, bytes"),
      [ACTION_RECEIVE_WALLET_FRAGMENT, fragData as `0x${string}`]
    )

    runtime.log("Sending wallet fragment report to proxy...")
    const fragReportResponse = runtime
      .report({
        encodedPayload: hexToBase64(fragReport),
        encoderName: "evm",
        signingAlgo: "ecdsa",
        hashingAlgo: "keccak256",
      })
      .result()

    evmClient
      .writeReport(runtime, {
        receiver: config.proxyAddress,
        report: fragReportResponse,
        gasConfig: { gasLimit: config.gasLimit },
      })
      .result()

    runtime.log(`Wallet fragment #${fragmentCount} delivered!`)
  }

  // ── Step 9: Check capture conditions ──
  const totalClues = cluesReceived + 1
  runtime.log(`Clues: ${cluesReceived} on-chain + 1 new = ${totalClues} total (need 3)`)

  if (isCorrectCity && totalClues >= 3) {
    runtime.log(`CAPTURE! Player found Carmen in city ${carmenCity} with ${totalClues} clues.`)

    const captureData = encodeAbiParameters(
      parseAbiParameters("uint256, uint256, bytes32"),
      [missionId, carmenCity, salt]
    )
    const captureReport = encodeAbiParameters(
      parseAbiParameters("uint8, bytes"),
      [ACTION_RESOLVE_CAPTURE, captureData as `0x${string}`]
    )

    const captureReportResponse = runtime
      .report({
        encodedPayload: hexToBase64(captureReport),
        encoderName: "evm",
        signingAlgo: "ecdsa",
        hashingAlgo: "keccak256",
      })
      .result()

    evmClient
      .writeReport(runtime, {
        receiver: config.proxyAddress,
        report: captureReportResponse,
        gasConfig: { gasLimit: config.gasLimit },
      })
      .result()

    runtime.log("Carmen captured! Mission complete!")
  }

  return {}
}

// ============================================================
//  Workflow initialization
// ============================================================
const initWorkflow = (config: Config) => {
  const network = getNetwork({
    chainFamily: "evm",
    chainSelectorName: config.chainSelectorName,
    isTestnet: true,
  })
  if (!network) throw new Error(`Network not found: ${config.chainSelectorName}`)

  const evmClient = new EVMClient(network.chainSelector.selector)
  const eventHash = keccak256(toBytes("InvestigationSubmitted(uint256,address,uint256)"))

  return [
    handler(
      evmClient.logTrigger({
        addresses: [hexToBase64(config.gameMasterAddress)],
        topics: [{ values: [hexToBase64(eventHash)] }],
      }),
      onInvestigationSubmitted
    ),
  ]
}

export async function main() {
  const runner = await Runner.newRunner<Config>()
  await runner.run(initWorkflow)
}

// generateAIClue not exported — Javy WASM does not support exported functions with parameters
